vito_raumtemperatur_soll:
  name: "Raumtemperatur soll"
  min: 3 # valid range starts at 3°C
  max: 35
  step: 1
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  mode: slider
vito_raumtemperatur_reduziert_soll:
  name: "Raumtemperatur reduziert soll"
  min: 3 # valid range starts at 3°C
  max: 35
  step: 1
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  mode: slider
vito_warmwasser_soll:
  name: "Warmwassertemperatur soll"
  min: 10 # valid range starts at 10°C
  max: 60 # valid range ends at 60°C
  step: 1
  icon: "mdi:thermometer"
  unit_of_measurement: "°C"
  mode: box
